export enum ManagerEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  TRANSFER = 'TRANSFER',
  BLOGGER = 'BLOGGER',
  MANAGER_PRODUCT = 'MANAGER_PRODUCT',
}

export enum RolesEnum {
  HOUSE_WIFE = 'HOUSE_WIFE',
  WHOLESALER = 'WHOLESALER',
  SHOPKEEPER = 'SHOPKEEPER',
  SPREADER = 'SPREADER',
}
